schema_version: 1

context:
  version: "0.1.3"

package:
  name: sphinx-fuma
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/s/sphinx-fuma/sphinx_fuma-${{ version }}.tar.gz
  sha256: ea3ef40e2848caf11117caee985510242f2a0bfb94c2507a0b74d2437d5e350f

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  host:
    - hatchling
    - pip
    - python ${{ python_min }}.*
  run:
    - python >=${{ python_min }}
    - sphinx >=7.2.6,<9
    - sphinx-searchlite

tests:
  - python:
      imports:
        - sphinx_fuma
      python_version:
        - ${{ python_min }}.*
        - "*"
      pip_check: true

about:
  homepage: https://github.com/python-project-templates/sphinx-fuma
  summary: Fumadocs theme for Sphinx
  license: Apache-2.0 AND OFL-1.1
  license_file:
    - LICENSE
    - sphinx_fuma/static/fonts/Geist-LICENSE.txt
    - sphinx_fuma/static/fonts/JetBrainsMono-LICENSE.txt
  repository: https://github.com/python-project-templates/sphinx-fuma

extra:
  recipe-maintainers:
    - timkpaine
